language: c
compiler:
    - gcc
    - clang
script: "sudo apt-get install libev-dev && ./configure && make"
branches:
    only:
        - master
notifications:
    recipients:
        - max.c.lv@gmail.com
    email:
        on_success: change
        on_failure: always
